// <auto-generated />
namespace ConstellationStore.Contracts.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Basket : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Basket));
        
        string IMigrationMetadata.Id
        {
            get { return "201603191358445_Basket"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
